config/routes.rb
Pinteresting::Application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"

  get "home" => "pages#home"
  get "about" => "pages#about"
  get "whoa" => "pages#whoa"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
     belongs_to :user
     has_attached_file :image, :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "100x100>" }

     validates :description, presence: true

     validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

  def whoa
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation" style="text-align:center;">
		<ul class="nav navbar-nav" style="display:inline-block;float:none;">
			<li style="font-size:10px;"><%= link_to "About Pinteresting", about_path %></li>
			<li style="font-size:10px;"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
		</ul>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="height: 43px; padding-left: 48px; padding-right: 55px;">
  <div class="container-fluid">
    <div class="container-fluid">

      <div class="navbar-header">

        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand" href=/ style="font-family: 'Playball';font-size: 32px;padding-top:10px;"> Pinteresting </a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >


        <ul class="nav navbar-nav navbar-right" style="padding-top:13px;" <%#hover="background-color: red;"%>>

            <li>
              <%= link_to root_path do %>
                <span class="fa fa-home fa-lg"></span> Home
              </a>
              <% end %>
            </li>

          <% if user_signed_in? %>
            <%#method 2 to add a glyphicon %>
              <li class="home">
                <%= link_to new_pin_path do %>
                  <span class="fa fa-plus fa-lg"></span> New Pin
                <% end %>
              </li>

          <% else %>
              <li class="home"><%= link_to "Sign Up", new_user_registration_path %></li>
              <li class="home"><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>

          <li class="dropdown home"> <%#necessary for dropdown%>
            <a href="#" <%#turns default cursor into "pointing hand" cursor when hovering over link%>
                                                        class="dropdown-toggle" data-toggle="dropdown">
              <span class="caret"></span></a> <%#necessary for dropdown%>
              <ul class="dropdown-menu" role="menu" style="position:fixed;top:42px;right:70px;"> <%#necessary for dropdown %>
                  <li>
                    <%= link_to about_path do %>
                      <span class="fa fa-question fa-lg"></span> About Us
                    <%end%>
                  </li>
                <% if user_signed_in? %>
                  <li class="divider"></li>
                  <li>
                    <%= link_to edit_user_registration_path do %>
                      <span class="fa fa-cog fa-lg"></span> Account Settings
                    <% end %>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to destroy_user_session_path, method: :delete do %>
                      <span class="fa fa-sign-out fa-lg"></span> Log Out
                    <%end%>
                  </li>
                <% end %>
              </ul>
          </li>

        </ul>
      </div>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
	<head>
		<%= favicon_link_tag 'logo.png' %>
		<style>
			p.ex {color: #026411;}
			a.one:link {color:#026420;text-decoration:none; padding: 0px;}
			a.one:visited {color:#026411;text-decoration:none;}
			a.one:hover {color:white;text-decoration:none;}
			a.one {font-family: 'Nosifer';font-size:48px;}
			p.link {text-align: center;}

		</style>
	  <title>Pinteresting</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>

	<body>

		<%= render 'layouts/header' %>

		<div class="container-fluid">
			<div class="container-fluid">
				<div class="jumbotron center" style="padding-top:5px;">
					<% flash.each do |name, msg| %>
						<%= content_tag(:div, msg, class: "alert alert-info") %>
					<% end %>
					<%= yield %>
				</div>

			</div>
		</div>
	</body>

	<p class="link">
		<b>
			<a class="one" href="/whoa">Whoa!</a>
		</b>
	</p>

	<p style="text-align:center;color:white;">© 2014. All Rights Reserved.</p>


		<%= render 'layouts/footer' %>

</html>

app/views/pages/_home.html.erb
<div class="panel panel-default">
 	<div class="panel-heading">
    	<div class="panel-title">
			<% if user_signed_in? %>
				<h1>Pins</h1>
		    	<%= link_to "Create Pin", new_pin_path, class: "btn btn-default btn-lg" %>
		    	<%= link_to "My Pins", pins_path, class: "btn btn-default btn-lg" %>
		  	<% else %>
		  		<h1>Welcome</h1>
		  		<p>Join Pinteresting to find (and save!) all the things that inspire you.</p>
				<p>
					<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default btn-lg" %>
					<%= link_to "Sign In", new_user_session_path, class: "btn btn-primary btn-lg" %>
				</p>
			<% end %>
		</div>
	</div>
</div>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
	We, the
	<%= link_to 'CodeTheDream Team', 'http://www.codethedream.org/', target: '_blank' %>,
	are working on our
	<%= link_to 'One Month Rails', 'https://onemonth.com/courses/one-month-rails', target: '_blank' %>
	pinteresting apps.
</p>
<p>Everyone in CodeTheDream made their own version of pinteresting.</p>
<p>Check out my <%= link_to "profile!", "http://cruznunez.io", class: "about", target: "_blank" %></p>

<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;">
    <span>Look at this amazing little animated progress bar. We could watch this all day.</span>
  </div>
</div>

app/views/pages/susi.html.erb
<h1>What the...!</h1>

<p>So you found the secret link....<p>
<p>Nice.</p>
<p>Now leave this place. You are not welcome here.</p>
<p>Oh btw Cruz is the best</p>
<p>P.S. SLI is awesome.</p>
<p>P.S.S. Martha is a dork. :p (It's true)</p>
<%= link_to pins_path do %>
      <span class="glyphicon glyphicon-arrow-left"></span>Back
<% end %>
<%#p>Oh btw Diego is a feg 8===D~~~</p>

<%#= do |f| %>
	<%#div class="field">
	    <%= f.label :description %><%#br>
	    <%#= f.text_field :description %>
	<%#/div>
<%# end %>

app/views/pages/whoa.html.erb
<h1>What the...!</h1>

<p>So you found the secret link....<p>
<p>Nice.</p>
<p>Now leave this place. You are not welcome here.</p>
<p>Oh btw Cruz is the best</p>
<%= link_to pins_path do %>
      <span class="fa fa-arrow-left"></span>Back
<% end %>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %><br/>
        <strong><%= pin.user.name if pin.user %></strong>
        <% if current_user && pin.user == current_user %>

          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="fa fa-pencil-square-o fa-lg"></span>
              Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="fa fa-trash-o"></span>
              Delete
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p>
  <%= @pin.description %>
</p>

<p>
  <% if current_user && @pin.user == current_user %>
    <%= link_to edit_pin_path(@pin) do %>
      <span class="fa fa-pencil-square-o fa-lg"></span>Edit
    <% end %>
  <% end %>
  <%= link_to pins_path do %>
      <span class="fa fa-arrow-left"></span>Back
  <% end %>
</p>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <img style="max-width:100%;height:auto;" href=raw<%=image_tag@pin.image.url %>
      </div>
      <div class="panel-body">
        <p><%= @pin.description %></p>
        <p><strong><%= @pin.user.name if @pin.user %></strong></p>
      </div>
    </div>
  </div>
</div>

<p>
	<% if current_user && @pin.user == current_user %>
    <%= link_to edit_pin_path(@pin) do %>
      <span class="fa fa-pencil-square-o fa-lg"></span>Edit
    <% end %>
	<% end %>
  <%= link_to pins_path do %>
      <span class="fa fa-arrow-left"></span>Back
  <% end %>
</p>